baseurl = "/"
MetaDataFormat = "yaml"
contentdir = "content"
layoutdir = "layouts"
publishdir = "../_public"
title = "sircus"
copyright = "Copyright (c) 2015 blivesta and ungki. all rights reserved."
pygmentsuseclasses = true

[params]
  description = "A scalable css for people who make web together"
  author = "blivesta"
  maintainer = "ungki"
  tags = "sircus, scalable css"
  sircus_url = "http://sircus.blivesta.com"
  github_url = "https://github.com/sircus/sircus"
  twitter = "blivesta"
  git_star_btn = "http://ghbtns.com/github-btn.html?user=sircus&repo=sircus&type=watch&count=true"
